### ISSUE TITLE
[LESS] max produit

### ISSUE THREAD

**Issue by cirelevuahc** [mickwan/3WA-Ecommerce#10]
http://192.168.1.10/developpement/PHP/eshop/index.php?page=product&id_product=3

 Fatal error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 72 bytes) in /home/was707/sites/developpement/PHP/eshop/models/Cart.class.php on line 113

<input type="number" max="20000000" min="1" name="quantity" class="input">
Et 20000000 dans le champs Quantity

**Comment by mickwan** [comment]
Fait!
