### ISSUE TITLE
[less] quantite achat produit

### ISSUE THREAD

**Issue by Shadownest** [mickwan/3WA-Ecommerce#15]
http://192.168.1.10/developpement/PHP/eshop/index.php?page=product&id_product=4
Sur la page d'achat du produit, en mettant 99999 dans l'input :D (après avoir virer le max de l'input)
![Image](http://image.prntscr.com/image/08993f2816e542348c42dc7b74ab3979.png)

**Comment by mickwan** [comment]
Fait!
