### ISSUE TITLE
[less] panier vide mais payant

### ISSUE THREAD

**Issue by Shadownest** [mickwan/3WA-Ecommerce#16]
http://192.168.1.10/developpement/PHP/eshop/index.php?page=current_cart
J'ai supprimé les éléments de mon panier, du coup y'a plus de produit dedans, mais j'ai quand même un prix ?
![Image](http://image.prntscr.com/image/b31c8c8305e949a4a76c43d07a1ab559.png)

**Comment by Steph67stbg** [comment]
FAIT!
