### ISSUE TITLE
[less] id panier incorrect

### ISSUE THREAD

**Issue by Shadownest** [mickwan/3WA-Ecommerce#17]
http://192.168.1.10/developpement/PHP/eshop/index.php?page=old_cart&id_cart=0
En modifiant id_cart dans l'url :
![Image](http://image.prntscr.com/image/fb99495678df4f51bb45fa57b4936086.png)
Et en supprimant complètement l'id_cart :
http://192.168.1.10/developpement/PHP/eshop/index.php?page=old_cart
![Image](http://image.prntscr.com/image/5123a0a6e3d54e69a6150fa044b8c5ca.png)

**Comment by mickwan** [comment]
Fait!
