### ISSUE TITLE
[bug]

### ISSUE THREAD

**Issue by philippe-3wa** [mickwan/3WA-Ecommerce#2]
http://192.168.1.10/developpement/PHP/eshop/index.php?page=shop&id_cat=aaa

Catchable fatal error: Argument 1 passed to SubCategoryManager::findByCategory() must be an instance of Category, null given, called in /home/was707/sites/developpement/PHP/eshop/apps/contents/menu_sub_cat.php on line 3 and defined in /home/was707/sites/developpement/PHP/eshop/models/SubCategoryManager.class.php on line 34

quand on change la cat à la main

**Comment by mickwan** [comment]
Fait !
