### ISSUE TITLE
[CRITIC] page MEN

### ISSUE THREAD

**Issue by patson67** [mickwan/3WA-Ecommerce#3]
page=shop&id_cat=9999

Catchable fatal error: Argument 1 passed to SubCategoryManager::findByCategory() must be an instance of Category, null given, called in /home/was707/sites/developpement/PHP/eshop/apps/contents/menu_sub_cat.php on line 3 and defined in /home/was707/sites/developpement/PHP/eshop/models/SubCategoryManager.class.php on line 34

Passer id_cat dans URL manuellement à 9999

**Comment by mickwan** [comment]
Fait!
