### ISSUE TITLE
[less]

### ISSUE THREAD

**Issue by germain009** [mickwan/3WA-Ecommerce#6]
url : http://192.168.1.10/developpement/PHP/eshop/index.php?page=shop&id_cat=155555555

( ! ) Catchable fatal error: Argument 1 passed to SubCategoryManager::findByCategory() must be an instance of Category, null given, called in /home/was707/sites/developpement/PHP/eshop/apps/contents/menu_sub_cat.php on line 3 and defined in /home/was707/sites/developpement/PHP/eshop/models/SubCategoryManager.class.php on line 34

icrement dand l'id 

non connecté

**Comment by mickwan** [comment]
Fait !
